config/routes.rb
Rails.application.routes.draw do
  # Priority is based on order of creation: first created -> highest priority.
  # See how all your routes lay out with "rake routes".
  root 'stats#index'

  # setting both the aliased and non-aliased so nothing breaks if on/off
  get '/user_files/untagged' => 'user_files#untagged'
  get '/files/untagged' => 'user_files#untagged'
  get '/stream/:id' => 'user_files#stream', as: 'stream'

  resources :directories
  resources :user_files, path: 'files'
  resources :tags
  resources :categories
  resources :users
  resources :stats

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/search' => 'searches#index'

  match '*path' => redirect('/'), via: :all
end

app/models/user_file.rb
class UserFile < ActiveRecord::Base
  belongs_to :directory
  belongs_to :extension
  belongs_to :user

  has_and_belongs_to_many :tags

  validates :name,
            presence: true,
            length: { minimum: 1 }
  validates :directory,
            presence: true
  validates :user,
            presence: true

  def csv_tags
    tags.map(&:name).join(', ')
  end

  def csv_tags=(csv_list)
    self.tags = csv_list.split(/,\s*/).map do |name|
      Tag.where(name: name.chomp).first_or_create!
    end
  end
end

app/controllers/user_files_controller.rb
class UserFilesController < ApplicationController
  include UserFilesHelper

  before_action :user_auth

  def index
    results = files_table
    @my_files = results[:my_files]
    @my_public_files = results[:my_public_files]
    @public_files = results[:public_files]
    @remaining_files = current_user.admin ? results[:remaining_files] : []
  end

  def show
    file_and_metadata
  end

  def stream
    @file = UserFile.find(params[:id])
    send_file("#{@file.directory.name}/#{@file.name}",
              filename: @file.name, disposition: :inline,
              stream: true, range: true)
  end

  def edit
    file_and_metadata
  end

  def update
    @file = UserFile.find(params[:id])
    update_and_touch(@file, user_file_params)
  end

  # special case code for listing untagged files
  def untagged
    @files = UserFile.includes(:tags)
                     .where(tags_user_files: { user_file_id: nil })
    @n_files = @files.count
  end

  private

  def user_file_params
    params.require(:user_file).permit(:csv_tags)
  end

  def files_table
    mine = UserFile.where(user: current_user)
    others = UserFile.where.not(user: current_user)
    {
      my_files: mine.where(public: false),
      my_public_files: mine.where(public: true),
      public_files: others.where(public: true),
      remaining_files: others.where(public: false)
    }
  end

  def file_and_metadata
    @file = UserFile.find(params[:id])
    full_path = "#{@file.directory.name}/#{@file.name}"
    @tp = TIFFParser.new(full_path) if run_tiff_parser? @file
  end
end

app/helpers/user_files_helper.rb
module UserFilesHelper
  IMAGE_EXTENSIONS_EMBED = %w(bmp jpg jpeg png).freeze
  IMAGE_EXTENSIONS = IMAGE_EXTENSIONS_EMBED + %w(cr2 dng nef).freeze
  VIDEO_EXTENSIONS_EMBED = %w(mkv mov mp4).freeze
  VIDEO_EXTENSIONS = VIDEO_EXTENSIONS_EMBED + %w(avi flv mpeg mpg wmv).freeze

  IMAGE_EXTENSIONS_RUN_TIFF_PARSER = %w(arw cr2 dng nef tiff).freeze

  def embeddable_image_extension?(file)
    IMAGE_EXTENSIONS_EMBED.include? file.extension.name
  end

  def embeddable_video_extension?(file)
    VIDEO_EXTENSIONS_EMBED.include? file.extension.name
  end

  def get_embed_code(file)
    if embeddable_image_extension?(file)
      image_tag(stream_path(file), alt: file.name, class: 'fit-image')
    elsif embeddable_video_extension?(file)
      # TODO: video embedding *works* but loads the entire file into
      # memory on the server. attempting to stream a 1 GB file = bad.
      # disabling the embedding for now as we don't know how powerful
      # of a machine the server will be on

      # video_tag(stream_path(file), alt: file.name, controls: true)
      ''
    else
      ''
    end
  end

  def get_suggested_tags_file(file)
    # get blah from blah.txt (extension won't help with tag suggestions)
    base_file_name = File.basename(file.name, File.extname(file.name))
    get_suggested_tags(file.directory.name + File::SEPARATOR + base_file_name)
  end

  def format_metadata(tag_name, data)
    case tag_name
    when :ApertureValue
      "f/#{data[0].to_f / data[1]}"
    when :ExposureTime
      "#{data[0]}/#{data[1]}"
    when :FNumber
      "f/#{data[0].to_f / data[1]}"
    when :FocalLength
      "#{data[0] / data[1]} mm"
    else
      data
    end
  end

  def run_tiff_parser?(file)
    IMAGE_EXTENSIONS_RUN_TIFF_PARSER.include? file.extension.name
  end
end

app/views/user_files/_file.html.erb
<div class="row">
  <div class="col-sm-8">
    <%= render 'file_info' %>
  </div>
  <div id="tags_container" class="col-sm-4">
    <% if tags == :tags %>
      <%= render 'tags' %>
    <% elsif tags == :suggested %>
      Suggested tags: <%= get_suggested_tags_file(@file).join(', ') %>
    <% end %>
  </div>
</div>
<br />
<div class="row">
  <div id="file_content" class="col-sm-8">
    <% embed_code = get_embed_code(@file) %>
    <% if embed_code.empty? %>
      Unable to preview file.
      Perhaps previews aren't supported for this file type.
    <% else %>
      <%= embed_code %>
    <% end %>
  </div>
  <div id="secondary" class="col-sm-4">
    <% if secondary == :form %>
      <%= render 'form' %>
    <% end %>
  </div>
</div>

<% if @tp %>
  <%= render 'photo_metadata' %>
<% end %>

app/views/user_files/_file_info.html.erb
<div id="file_info">
  <%= link_to @file.directory.name, @file.directory %><br />
  <%= @file.name %>: <%= number_to_human_size @file.size %>
</div>

app/views/user_files/_file_list.html.erb
<div id="<%= ownership %>">
  <a data-toggle="collapse" href="#collapse_<%= ownership %>">
    <%= "#{ownership.titleize} Files (#{files.count})" %>
  </a>
  <br />
  <div id="collapse_<%= ownership %>" class="collapse">
    <% files.each do |file| %>
      <%= link_to file.name, file %><br />
    <% end %>
  </div>
</div>
<br />

app/views/user_files/_form.html.erb
<%= form_for(@file) do |f| %>
  <%= f.label :tags %>
  <%= f.text_field :csv_tags, class: 'form-control' %>
  <br />
  <%= f.submit 'Save', class: 'btn btn-primary' %>
<% end %>

app/views/user_files/_photo_metadata.html.erb
<div id="metadata">
  <% @tp.interesting_records.each do |type, list| %>
    <h4><%= type.to_s.titleize %></h4>
    <% list.each do |rec| %>
      <%= "#{rec.tag_name}: #{format_metadata(rec.tag_name, rec.data)}" %><br />
    <% end %>
  <% end %>
</div>

app/views/user_files/_tags.html.erb
<div id="tags">
  Tags:
  <% @file.tags.each do |tag| %>
    <%= link_to tag.name, tag %>
  <% end %>
</div>

<div id="edit">
  <%= link_to "Edit", edit_user_file_path(@file) %>
</div>

app/views/user_files/edit.html.erb
<%= render 'file', tags: :suggested, secondary: :form %>

app/views/user_files/index.html.erb
<%= link_to 'See untagged files', user_file_path('untagged') %>
<br />
<br />
<div id="anchor_links">
  <%= get_anchor_links_raw(['private', 'my_public', 'public', 'all_remaining'],
                           :titleize).join(', ').html_safe %>
</div>
<br />
<%= render 'file_list', ownership: 'private', files: @my_files %>
<%= render 'file_list', ownership: 'my_public', files: @my_public_files %>
<%= render 'file_list', ownership: 'public', files: @public_files %>
<%= render 'file_list', ownership: 'all_remaining', files: @remaining_files %>

app/views/user_files/show.html.erb
<%= render 'file', tags: :tags, secondary: nil %>

app/views/user_files/untagged.html.erb
<div id="file_list">
  <%= "#{@n_files} untagged files" %>
  <%= link_to 'See all files', user_files_path %>
  <br />
  <br />
  <% @files.each do |file| %>
    <%= link_to file.name, edit_user_file_path(file) %><br />
  <% end %>
</div>