config/routes.rb
Rails.application.routes.draw do
  # Priority is based on order of creation: first created -> highest priority.
  # See how all your routes lay out with "rake routes".
  root 'stats#index'

  # setting both the aliased and non-aliased so nothing breaks if on/off
  get '/user_files/untagged' => 'user_files#untagged'
  get '/files/untagged' => 'user_files#untagged'
  get '/stream/:id' => 'user_files#stream', as: 'stream'

  resources :directories
  resources :user_files, path: 'files'
  resources :tags
  resources :categories
  resources :users
  resources :stats

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/search' => 'searches#index'

  match '*path' => redirect('/'), via: :all
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_files

  has_secure_password

  validates :name,
            presence: true,
            uniqueness: true

  def self.digest(str)
    # need to figure out the cost because while in dev/testing, activemodel
    # switches to a minimal cost, as bcrypt is designed to be computationally
    # expensive (for security purposes). don't need great security during dev.
    cost = if ActiveModel::SecurePassword.min_cost
             BCrypt::Engine::MIN_COST
           else
             BCrypt::Engine.cost
           end

    BCrypt::Password.create(str, cost: cost)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # admin_auth defined in application_controller.rb
  before_action :admin_auth

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  def index
    @admins = User.where(admin: true)
    @regulars = User.where(admin: false)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(
      :name, :admin, :password,
      :password_confirmation
    )
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= render 'shared/error', obj: @user %>

<div id="user_form" class="col-sm-6">
  <%= form_for(@user) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
    <br />
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
    <br />
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
    <br />
    <%= f.label :admin %>
    <%= f.check_box :admin %>
    &nbsp;
    <%= f.submit 'Create User', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/users/_user_list.html.erb
<div>
  <h2><%= type.pluralize.titleize %></h2>
</div>

<div id="<%= type %>_list">
  <ul>
  <% list.each do |user| %>
    <li><%= link_to user.name, user %></li>
  <% end %>
  </ul>
</div>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<div id="user_management">
  <%= link_to "Create new user", new_user_path %>
</div>

<%= render 'user_list', type: 'admin', list: @admins %>
<%= render 'user_list', type: 'regular_user', list: @regulars %>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<div id="user_info">
  <h1><%= @user.name %></h1>
  <% if @user.admin %>
    User is an administrator
    <br />
  <% end %>
  <%= link_to 'Edit', edit_user_path(@user) %>
  <br />
  <%= link_to 'Delete', user_path(@user), method: :delete %>
  <br />
  <%= link_to 'Back to user list', users_path %>
</div>

<br />

<div id="user_files">
  <% @user.user_files.each do |file| %>
    <%= link_to file.name, file %><br />
  <% end %>
</div>