config/routes.rb
Rails.application.routes.draw do
  # Priority is based on order of creation: first created -> highest priority.
  # See how all your routes lay out with "rake routes".
  root 'stats#index'

  # setting both the aliased and non-aliased so nothing breaks if on/off
  get '/user_files/untagged' => 'user_files#untagged'
  get '/files/untagged' => 'user_files#untagged'
  get '/stream/:id' => 'user_files#stream', as: 'stream'

  resources :directories
  resources :user_files, path: 'files'
  resources :tags
  resources :categories
  resources :users
  resources :stats

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/search' => 'searches#index'

  match '*path' => redirect('/'), via: :all
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :extensions

  validates :name,
            presence: true,
            uniqueness: true

  def csv_extensions
    extensions.map(&:name).join(', ')
  end

  def csv_extensions=(csv_list)
    self.extensions = csv_list.split(/,\s*/).map do |ext|
      Extension.where(name: ext.chomp).first_or_create!
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  include CategoriesHelper
  before_action :user_auth
  before_action :admin_auth, only: [:new, :create, :edit, :destroy]
  after_action :collect_unsorted_extensions, only: [:create, :destroy, :update]

  def index
    @cats = Category.all
  end

  def new
    @cat = Category.new
  end

  def edit
    @cat = Category.find(params[:id])
  end

  def show
    @cat = Category.find(params[:id])
    @exts = @cat.extensions.order(:name)
    @files_by_ext = files_by_ext
    @n_files_in_cat = @files_by_ext.values.map(&:count).reduce(&:+) || 0
  end

  def destroy
    cat = Category.find(params[:id])
    # TODO: need a better way of identifying this special category
    if cat.name == 'Unsorted'
      flash[:info] = 'This is the collector category and should not be deleted.'
      redirect_to cat
    else
      cat.destroy
      redirect_to categories_path
    end
  end

  def create
    @cat = Category.new(category_params)
    if @cat.save
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def update
    @cat = Category.find(params[:id])
    if @cat.update_attributes(category_params)
      redirect_to @cat
    else
      render 'edit'
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :csv_extensions)
  end

  def files_by_ext
    cat_files = {}
    @exts.each { |ext| cat_files[ext.name] = visible_files(ext.user_files) }
    cat_files
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def collect_unsorted_extensions
    cat = Category.where(name: 'Unsorted').first
    cat.extensions << Extension.where(category_id: nil)
  end
end

app/views/categories/_form.html.erb
<%= render 'shared/error', obj: @cat %>

<div id="category_form" class="col-sm-6">
  <%= form_for(@cat) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
    <br />
    <%= f.label 'File types' %>
    <%= f.text_field :csv_extensions, class: 'form-control' %>
    <br />
    <%= f.submit 'Save', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/categories/edit.html.erb
<%= render 'form' %>

app/views/categories/index.html.erb
<div id="category_list">
  <% @cats.each do |cat| %>
    <%= link_to cat.name, cat %><br />
  <% end %>
</div>

<div id="category_management">
  <%= link_to "Create new category", new_category_path %>
</div>

app/views/categories/new.html.erb
<%= render 'form' %>

app/views/categories/show.html.erb
<div id="category_info">
  <h1><%= @cat.name %></h1>

  Extensions:
  <%= get_anchor_links(:name, @exts).join(', ').html_safe %>
  <% if current_user.admin %>
    |
    <%= link_to 'Edit', edit_category_path(@cat) %>
    <%= link_to 'Delete', category_path(@cat), method: :delete %>
  <% end %>
  <br />
  <br />
  <%= "#{@n_files_in_cat} files in this category" %>
</div>

<div id="category_files">
  <% @files_by_ext.each do |ext, file_list| %>
    <a id="<%= ext %>" data-toggle="collapse" href="#collapse_<%= ext %>">
      <h5><%= "#{ext} (#{file_list.length})" %></h5>
    </a>
    <div id="collapse_<%= ext %>" class="collapse">
      <% file_list.each do |file| %>
        <%= link_to file.name, file %><br />
      <% end %>
    </div>
  <% end %>
</div>