config/routes.rb
Rails.application.routes.draw do
  # Priority is based on order of creation: first created -> highest priority.
  # See how all your routes lay out with "rake routes".
  root 'stats#index'

  # setting both the aliased and non-aliased so nothing breaks if on/off
  get '/user_files/untagged' => 'user_files#untagged'
  get '/files/untagged' => 'user_files#untagged'
  get '/stream/:id' => 'user_files#stream', as: 'stream'

  resources :directories
  resources :user_files, path: 'files'
  resources :tags
  resources :categories
  resources :users
  resources :stats

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/search' => 'searches#index'

  match '*path' => redirect('/'), via: :all
end

app/views/layouts/_category_dropdown.html.erb
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    Categories <span class="caret"></span>
  </a>
  <ul class="dropdown-menu">
    <% Category.all.sort_by(&:name).each do |cat| %>
      <li><%= link_to cat.name, cat %></li>
    <% end %>
    <% if current_user.admin %>
      <li role="separator" class="divider"></li>
      <li><%= link_to 'New Category', new_category_path %></li>
    <% end %>
  </ul>
</li>

app/views/layouts/_settings_dropdown.html.erb
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    Settings <span class="caret"></span>
  </a>
  <ul class="dropdown-menu">
    <li><%= link_to 'Users', users_path %></li>
  </ul>
</li>

app/views/layouts/_top_menu.html.erb
<header class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <%= link_to 'ProjectFIREBALL', root_path, id: 'home_link' %>
    <ul class="nav navbar-nav navbar-right">
      <% if logged_in? %>
        <li><%= link_to 'Directories', directories_path %></li>
        <li><%= link_to 'Files', user_files_path %></li>
        <li><%= link_to 'Tags', tags_path %></li>
        <li class="navbar-text">|</li>
        <%= render 'layouts/category_dropdown' %>
        <li class="navbar-text">|</li>

        <% if current_user.admin %>
          <%= render 'layouts/settings_dropdown' %>
          <li class="navbar-text">|</li>
        <% end %>

        <li><%= link_to 'Logout', logout_path, method: :delete %></li>
      <% else %>
        <li><%= link_to 'Login', login_path %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjectFIREBALL</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="http://dimplejs.org/dist/dimple.v2.2.0.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/top_menu' %>
<%= render 'shared/flash_output' %>

<div id="main_content" class="container">
  <%= yield %>
</div>

</body>
</html>